// This should produce an error: continue outside loop
print "This will error";
continue;